/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

// Create Express App
const app = express();
app.use(express.json());

const PORT = 3000;

// Lazy instantiation of GoogleGenAI client to prevent crashes if key is initially empty
let aiClient: GoogleGenAI | null = null;
function getGenAI(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY environment variable is not configured.');
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

// Full-stack API routes FIRST
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', time: new Date().toISOString() });
});

// AI analysis proxy route
app.post('/api/analyze-gemini', async (req, res) => {
  const { emailText, mlVerdict, confidence, scores } = req.body;

  if (!emailText) {
    return res.status(400).json({ error: 'Email text is required.' });
  }

  try {
    const ai = getGenAI();
    
    // Construct rich prompt
    const prompt = `You are a professional Phishing Analysis AI Consultant on an interactive Machine Learning cybersecurity dashboard.
Analyze the following email and explain why it was flagged.

--- EMAIL TEXT ---
${emailText}

--- MACHINE LEARNING MODEL ANALYSIS ---
Model classification verdict: **${mlVerdict.toUpperCase()}**
Model decision confidence: **${(confidence * 100).toFixed(1)}%**
Heuristic metrics:
- Suspicious keyword weight count: ${scores?.suspiciousKeywordCount || 0}
- Link count: ${scores?.linkCount || 0}
- Urgency signals: ${scores?.urgencyLevel || 'N/A'}

Please provide a highly polished, bite-sized security audit in Markdown. Use clean bullet points and clear typography:
1. **Social Engineering Tactics Detected**: What behavioral psychology is used (e.g. artificial urgency, panic trigger, authority impersonation)?
2. **Technical Red Flags**: Mismatching URLs, suspicious domains, IP addresses, lack of security variables.
3. **Safety Advice Checklist**: 3 quick, crisp protective actions the recipient must take.

Be direct, professional, and objective. Limit response to 3-4 clean sentences per section.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
    });

    const explanation = response.text || 'No explanation could be generated by the Gemini model.';
    res.json({ explanation });
  } catch (err: any) {
    console.error('Error in /api/analyze-gemini:', err?.message || err);
    res.status(500).json({ 
      error: 'Failed to generate AI security analysis.',
      details: err?.message || 'Is your GEMINI_API_KEY configured in Settings > Secrets?' 
    });
  }
});

// Setup Vite Dev Server / Static Assets
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    // Use Vite's connect instance as middleware
    app.use(vite.middlewares);
  } else {
    // Serve static files in production
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server starting on http://localhost:${PORT}`);
  });
}

startServer().catch(err => {
  console.error('Failed to start full-stack server:', err);
});
